# Generated by Django 5.2.11 on 2026-02-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True, verbose_name='User ID')),
                ('error_type', models.CharField(max_length=255, verbose_name='Xato turi')),
                ('message', models.TextField(verbose_name='Xato xabari')),
                ('stack_trace', models.TextField(blank=True, null=True, verbose_name="To'liq xato (Traceback)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
            ],
            options={
                'verbose_name': 'Xatolik logi',
                'verbose_name_plural': 'Xatolik loglari',
            },
        ),
        migrations.CreateModel(
            name='MediaStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Media kaliti')),
                ('link', models.URLField(verbose_name='Telegram xabar linki')),
            ],
            options={
                'verbose_name': 'Media ombori',
                'verbose_name_plural': 'Media ombori',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Vakansiya nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nomzod F.I.SH')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('answers', models.JSONField(default=dict, verbose_name='Barcha javoblar (JSON)')),
                ('video_note_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Video File ID')),
                ('voice_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Voice File ID')),
                ('video_note_file', models.FileField(blank=True, null=True, upload_to='candidates/videos/%Y/%m/', verbose_name='Aylana video (Fayl)')),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='candidates/voices/%Y/%m/', verbose_name='Ovozli xabar (Fayl)')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('review', "Ko'rib chiqilmoqda"), ('interview', 'Suhbatga tayinlandi'), ('rejected', 'Rad etildi'), ('hired', 'Ishga olindi')], default='new', max_length=20, verbose_name='Holati')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='models.vacancy', verbose_name='Vakansiya')),
            ],
            options={
                'verbose_name': 'Nomzod',
                'verbose_name_plural': 'Nomzodlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
